### ISSUE TITLE
apt package for Ubuntu

### ISSUE THREAD

**Issue by mzieg** [WasatchPhotonics/ENLIGHTEN#104]
We should try to support "standard package deployment mechanisms" for different operating systems.  For Ubuntu, I think that would be an apt package.  For MacOS, perhaps Homebrew?  I would like to start with Ubuntu as that is a widely-requested platform.

**Comment by mzieg** [comment]
This relates to the following snippet from a customer issue installing and running on Ubuntu:

> I renamed the libusb library, its defaulting to:
> 
> ```
> Traceback (most recent call last):
>   File "wasatch/WasatchBus.py", line 50, in update
>   File "wasatch/DeviceFinderUSB.py", line 54, in find_usb_devices
>   File "usb/core.py", line 1292, in device_iter
>   File "usb/backend/libusb0.py", line 456, in enumerate_devices
>   File "ctypes/__init__.py", line 387, in __getattr__
>     func = self.__getitem__(name)
>   File "ctypes/__init__.py", line 392, in __getitem__
>     func = self._FuncPtr((name_or_ordinal, self))
> AttributeError: /home/odi-developer/Downloads/ENLIGHTEN-3.2.6/libusb-1.0.so.0: undefined symbol: usb_find_busses
> ```
> 
> I then renamed all the libusb libraries and copied over the libusb-0.1.so.4 from the native libraries directory, and that seemed to do the trick. 
> 
> I swapped back to the libusb-1.0 and still same error. I'm guessing only libusb-0.1 will work?
