### ISSUE TITLE
Windows installer not seeing libusb0 backend

### ISSUE THREAD

**Issue by mzieg** [WasatchPhotonics/ENLIGHTEN#307]
Talks to spectrometers fine when run from source, back to giving this from Windows installer :-(
```
2023-10-06 10:14:11,799 [0x00000de8] wasatch.WasatchBus DEBUG    USBBus.update: instantiating DeviceFinderUSB
2023-10-06 10:14:11,799 [0x00000de8] wasatch.DeviceFinderUSB DEBUG    DeviceFinderUSB.find_usb_devices: starting
2023-10-06 10:14:11,799 [0x00000de8] wasatch.DeviceFinderUSB DEBUG    DeviceFinderUSB.find_usb_devices: just doing a bus poll for startup_scan 0
2023-10-06 10:14:11,799 [0x00000de8] wasatch.WasatchBus CRITICAL LIBUSB error
Traceback (most recent call last):
  File "wasatch\WasatchBus.py", line 52, in update
  File "wasatch\DeviceFinderUSB.py", line 172, in find_usb_devices
  File "wasatch\DeviceFinderUSB.py", line 90, in bus_polling
  File "usb\core.py", line 1309, in find
usb.core.NoBackendError: No backend available
```

**Comment by mzieg** [comment]
Tentatively closing as #308 seems to resolve on Win10 and Win11 from installer.
