### ISSUE TITLE
disconnecting/reconnecting breaks Save/Clipboard button

### ISSUE THREAD

**Issue by samiebee43** [WasatchPhotonics/ENLIGHTEN#98]
Similarly, disconnecting and reconnecting a single time breaks the Save button.

```
Traceback (most recent call last):
  File "C:\Users\sbee\Projects\ENLIGHTEN\enlighten\VCRControls.py", line 182, in save
    callback()
  File "C:\Users\sbee\Projects\ENLIGHTEN\enlighten\Controller.py", line 1101, in save_current_spectra
    self.measurements.create_from_spectrometer(spec=spec, view=view)
  File "C:\Users\sbee\Projects\ENLIGHTEN\enlighten\Measurements.py", line 237, in create_from_spectrometer
    measurement = self.factory.create_from_spectrometer(
  File "C:\Users\sbee\Projects\ENLIGHTEN\enlighten\MeasurementFactory.py", line 92, in create_from_spectrometer
    measurement = Measurement(
  File "C:\Users\sbee\Projects\ENLIGHTEN\enlighten\Measurement.py", line 319, in __init__
    self.view               = spec.app_state.technique_name
AttributeError: 'SpectrometerApplicationState' object has no attribute 'technique_name'
```

_Originally posted by @samiebee43 in https://github.com/WasatchPhotonics/ENLIGHTEN/issues/97#issuecomment-1414277882_

**Comment by samiebee43** [comment]
Steps to reproduce bug
1. Start ENLIGHTEN with a connected Spectrometer
2. Disconnect the Spectrometer
3. Reconnect the Spectrometer
4. Click the Save to clipboard button

Outcome
No new image is saved

Workaround
1. Click Non-Raman Tab
2. Click back to Raman Tab

**Comment by samiebee43** [comment]
Hints..
https://github.com/WasatchPhotonics/ENLIGHTEN/blob/3190eb5b9c7e26a876554a9b0079b6a2bce9e277/enlighten/PageNavigation.py#L252-L264

`spec.app_state.technique_name` is defined whenever `set_technique_common` is called. It is invoked when the technique is changed in the UI (which is why the workaround works) and it is probably called a startup.

When a spectrometer is disconnected and reconnected, we would lose spectrometer app state. And apparently reconnect is not being treated exactly like init. One solution would be to bind reconnecting to set_technique_common.

An alternative would be to move away from SpectrometerApplicationState, as I believe that thing was mostly there from when Enlighten was multiprocess instead of multithreaded. 

Measurement.py should be able to directly access the PageNav instance and grab an (added) technique_name field. The immediate way to do this would be to pass a reference to PageNav via Measurement's constructor in BusinessObjects.

Post-refactor, if component/instance ownership is moved to the BO level, then it would be fixed by referencing `self.ctl.page_nav.technique_name` from within Measurement.py

**Comment by samiebee43** [comment]
I suspect that this and #97 are duplicates of #111

**Comment by samiebee43** [comment]
fixed https://github.com/WasatchPhotonics/ENLIGHTEN/commit/526a30b88fcff3cf4616d63f43a8e3b30095a71e
